#!/usr/bin/env node
// build_figures.mjs — the repository's standalone figures, generated from data/.
//
//   node tools/build_figures.mjs           write the figures and the README banner block
//   node tools/build_figures.mjs --check   exit 1 if a figure or the README block is stale
//
// Figures (specs in figures/specs/, drawing code in site/src/lib/og/, the same
// modules that draw the site's Open Graph cards):
//   figures/banner-dark.svg     README banner, 1280 x 320: counts, runs per configuration,
//                               data date; text outlined so GitHub draws it without our fonts
//   figures/banner-light.svg    the dark file through the DESIGN.md token swap, never drawn apart
//   figures/social-preview.png  repository social preview, 1280 x 640 (uploaded by hand in the
//                               repository settings: GitHub has no API for it)
// README.md, between <!-- gen:banner --> and <!-- /gen:banner -->: a <picture> with the
// pair and an alt text generated from the same data.
//
// figures/figures.lock.json records, per figure, the SHA-256 of its SVG source (the
// drawing before the text is outlined, a pure function of data/, the specs, the fonts'
// metrics and DESIGN.md) and of the file written. --check rebuilds the sources only —
// it needs Node with type stripping (>= 22.18) but not the renderer — and fails when a
// source or a written file no longer matches the lock, or the README block differs.
// Writing needs site/node_modules (npm ci in site/) for @resvg/resvg-js.
// Exit status: 0 up to date (or written), 1 stale, 2 cannot run.
import { register } from 'node:module';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FIG = path.join(ROOT, 'figures');
const LOCK = path.join(FIG, 'figures.lock.json');
const README = path.join(ROOT, 'README.md');
const LIB = path.join(ROOT, 'site', 'src', 'lib');

const args = process.argv.slice(2);
if (args.includes('-h') || args.includes('--help')) {
  const src = fs.readFileSync(fileURLToPath(import.meta.url), 'utf8').split('\n');
  console.log(src.slice(1, src.findIndex((l) => l.startsWith('import'))).map((l) => l.replace(/^\/\/ ?/, '')).join('\n'));
  process.exit(0);
}
const unknown = args.filter((a) => a !== '--check');
if (unknown.length) {
  console.error(`build_figures: unknown argument ${unknown[0]} (see --help)`);
  process.exit(2);
}
const check = args.includes('--check');

if (!process.features?.typescript) {
  console.error(`build_figures: Node ${process.versions.node} cannot strip TypeScript types; Node >= 22.18 is required`);
  process.exit(2);
}

// The site's modules are written for Vite: extensionless relative imports and
// import.meta.env.BASE_URL. Two small hooks let plain Node load them unchanged.
const hook = String.raw`
export async function resolve(s, c, n) {
  try { return await n(s, c); } catch (e) {
    if ((s.startsWith('./') || s.startsWith('../')) && !/\.[cm]?[jt]s$/.test(s)) return n(s + '.ts', c);
    throw e;
  }
}
export async function load(u, c, n) {
  const r = await n(u, c);
  if (u.includes('/site/src/') && u.endsWith('.ts')) {
    return { ...r, source: 'if (!import.meta.env) import.meta.env = { BASE_URL: "/rtx3090fe-model-tests/" };\n' + String(r.source) };
  }
  return r;
}`;
register('data:text/javascript,' + encodeURIComponent(hook));
process.env.RTX_REPO_ROOT = ROOT;

const imp = (rel) => import(pathToFileURL(path.join(LIB, rel)).href);
const social = await imp('og/social.ts');
const tokens = await imp('og/tokens.ts');

const sha = (b) => createHash('sha256').update(b).digest('hex');
const rel = (p) => path.relative(ROOT, p);

// ---------------------------------------------------------------------------
// Sources (pure functions of the data) and the README block

const banner = social.bannerSvg();
const soc = social.socialSvg();
for (const [name, svg] of [['banner', banner.svg], ['social-preview', soc.svg]]) {
  const foreign = tokens.foreignColours(svg, tokens.dark());
  if (foreign.length) {
    console.error(`build_figures: ${name} uses colours outside the DESIGN.md tokens: ${foreign.join(', ')}`);
    process.exit(1);
  }
}

const escAttr = (s) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
const BEGIN = '<!-- gen:banner -->';
const END = '<!-- /gen:banner -->';
const block = [
  BEGIN,
  '<!-- Generated by tools/build_figures.mjs from data/. Do not edit by hand. -->',
  '<p align="center"><picture>',
  '  <source media="(prefers-color-scheme: dark)" srcset="figures/banner-dark.svg">',
  '  <source media="(prefers-color-scheme: light)" srcset="figures/banner-light.svg">',
  `  <img src="figures/banner-light.svg" width="1280" alt="${escAttr(banner.alt)}">`,
  '</picture></p>',
  END,
].join('\n');

function spliceReadme(text) {
  const a = text.indexOf(BEGIN);
  const b = text.indexOf(END);
  if (a >= 0 && b > a) return text.slice(0, a) + block + text.slice(b + END.length);
  if (a >= 0 || b >= 0) throw new Error('README.md has one banner marker without the other');
  return `${block}\n\n${text}`;
}

const sources = { 'banner-dark.svg': banner.svg, 'banner-light.svg': banner.svg, 'social-preview.png': soc.svg };

if (check) {
  const problems = [];
  let lock = null;
  try {
    lock = JSON.parse(fs.readFileSync(LOCK, 'utf8'));
  } catch {
    problems.push(`${rel(LOCK)} is missing or unreadable`);
  }
  if (lock) {
    for (const [file, src] of Object.entries(sources)) {
      const entry = lock.figures?.[file];
      const p = path.join(FIG, file);
      if (!entry) { problems.push(`figures/${file}: not in the lock`); continue; }
      if (entry.source_sha256 !== sha(src)) problems.push(`figures/${file}: stale (its data, spec, fonts or tokens changed)`);
      if (!fs.existsSync(p)) problems.push(`figures/${file}: missing`);
      else if (sha(fs.readFileSync(p)) !== entry.sha256) problems.push(`figures/${file}: edited by hand or not regenerated (hash differs from the lock)`);
    }
  }
  const readme = fs.readFileSync(README, 'utf8');
  try {
    if (spliceReadme(readme) !== readme) problems.push('README.md: the banner block is stale or missing');
  } catch (e) {
    problems.push(`README.md: ${e.message}`);
  }
  for (const p of problems) console.log(`STALE ${p}`);
  console.log(`build_figures --check: ${Object.keys(sources).length} figures and the README banner block, ${problems.length} problem(s)` +
    (problems.length ? '; run node tools/build_figures.mjs' : ''));
  process.exit(problems.length ? 1 : 0);
}

// ---------------------------------------------------------------------------
// Write

let render;
try {
  render = await imp('og/render.ts');
} catch (e) {
  console.error(`build_figures: cannot load the renderer (${e.message}); run npm ci in site/ first`);
  process.exit(2);
}
fs.mkdirSync(FIG, { recursive: true });
const darkSvg = render.outlineText(banner.svg);
if (/<text[\s>]/.test(darkSvg)) throw new Error('build_figures: text left un-outlined in the banner');
const outputs = {
  'banner-dark.svg': Buffer.from(darkSvg),
  'banner-light.svg': Buffer.from(tokens.swapToLight(darkSvg)),
  'social-preview.png': render.renderPng(soc.svg, Infinity),
};
const lock = {
  about: 'Written by tools/build_figures.mjs. source_sha256: the SVG drawn from data/ before rendering; sha256: the file written. Checked by node tools/build_figures.mjs --check.',
  figures: {},
};
for (const [file, buf] of Object.entries(outputs)) {
  fs.writeFileSync(path.join(FIG, file), buf);
  lock.figures[file] = { source_sha256: sha(sources[file]), sha256: sha(buf), bytes: buf.length };
  console.log(`wrote figures/${file} (${buf.length} bytes)`);
}
fs.writeFileSync(LOCK, `${JSON.stringify(lock, null, 2)}\n`);
const readme = fs.readFileSync(README, 'utf8');
const next = spliceReadme(readme);
if (next !== readme) {
  fs.writeFileSync(README, next);
  console.log('updated the README banner block');
}
console.log(`wrote ${rel(LOCK)}`);
